### ISSUE TITLE
 Full screen image problem

### ISSUE THREAD

**Issue by Citronnelledu33** [TeamShinkansen/Hakchi2-CE#279] opened 2020-01-15 15:22 UTC
Hello,

I just flashed my Megadrive Mini, everything works for now!

I spotted a small bug, when I go to the console settings to put in full screen, the image remains with the console wallpaper and does not go into full screen ...

It's a shame because it was very practical.

If you can do something, it will be cool!

Thank you

**Comment by Citronnelledu33** [comment] 2020-01-15 15:23
Excuse my english, I'am French... Google traduction

**Comment by codzon** [comment] 2020-01-19 12:45
> Hello,
> 
> I just flashed my Megadrive Mini, everything works for now!
> 
> I spotted a small bug, when I go to the console settings to put in full screen, the image remains with the console wallpaper and does not go into full screen ...
> 
> It's a shame because it was very practical.
> 
> If you can do something, it will be cool!
> 
> Thank you

I have the same issue , need help to make games full screen , I switched from Lunar to Hakchi CE and noticed this happen

**Comment by bslenul** [comment] 2020-01-19 17:57
It was fixed by madmonkey:
* Press Ctrl+F12 in hakchi CE to unlock the Developper menu.
* Settings > Developper tools > Download Latest Hakchi.
* And finally Kernel > Install / Repair.

The 16/9 mode should now work as intended.

**Comment by codzon** [comment] 2020-01-19 18:17
> It was fixed by madmonkey:
> 
> * Press Ctrl+F12 in hakchi CE to unlock the Developper menu.
> * Settings > Developper tools > Download Latest Hakchi.
> * And finally Kernel > Install / Repair.
> 
> The 16/9 mode should now work as intended.

It works, I appreciate your help, thank you :+1:

**Comment by Citronnelledu33** [comment] 2020-01-20 10:00
> It was fixed by madmonkey:
> 
> * Press Ctrl+F12 in hakchi CE to unlock the Developper menu.
> * Settings > Developper tools > Download Latest Hakchi.
> * And finally Kernel > Install / Repair.
> 
> The 16/9 mode should now work as intended.

It s good for me ! Thanks

**Closed as completed** 2020-11-29 23:13 UTC
Labels: bug
