### ISSUE TITLE
Adding NES Games results in wrong command line parameter

### ISSUE THREAD

**Issue by hoderer** [TeamShinkansen/Hakchi2-CE#30] opened 2018-02-20 14:15 UTC
Hey Guys! Glad someone took the 'dusty' original hakchi2 and made it even better! THANKS!

I noticed something. When adding NES Games to hakchi2 CE 1.1.0 the command line parameter is no longer working with the latest retroarch versions.

This is what happens after adding NES games - the command line looks something like this:
/bin/nes /var/games/...

This is what is needed:
/bin/fceumm /var/games/...
or
/bin/nestopia /var/games/...

Since there are two possibilites, a checkbox "use fceumm" or "use nestopia" would be quite useful or does somebody know another solution which is working with "/bin/nes"? It's a pain to edit the command line of hundreds of games... Maybe different retroarch versions with just one NES module would make it work with /bin/nes, too.

Thanks for any help on this.

**Comment by darkdev1** [comment] 2018-02-20 17:26
Hi,
Another solution which is working with `/bin/nes` is the USB-HOST.
Also the NESC works with `/bin/nes` unlike the SNESC.
To avoid editing the command line of hundreds of games, just use fnr.exe ( https://github.com/zzzprojects/findandreplace ) go to your Dir: `hakchi2\games_snes` , Find Only: `/bin/nes` then Replace: `/bin/fceumm`.

**Comment by hoderer** [comment] 2018-02-20 17:55
Perfect! Thanks alot. I remember watching a video of KMFDManic mentioning this tool a few months ago, but I simply forgot because I didn't need it at that time. Thanks for bringing it up again!

**Comment by daPhie79** [comment] 2018-02-20 18:33
i would really like to know the cause for this, because as far as i can see this, the /bin/nes command is included in retroarch, so it should work! it also works on my japanese sfc. i never witnessed this issue.

**Comment by KMFDManic** [comment] 2018-02-21 03:59
@darkdev1 Comme toujours, merci de me souvenir des connaissances que je vous ai transmises dans le passé, et d'aider les autres dans les moments plus actuels :) Merci, mon ami :)

@hoderer Long time no see:)

@daPhie79 Sur le NESC original, KachiKachi avait à l'origine des problèmes de chargement des ROM compressées. Cela pourrait très bien être l'ensemble du problème. J'ai encore un NESC, et si je trouve le temps je peux creuser plus dans le conflit de NESC pour NES. Mais ce n'est pas une affaire énorme. Vous pouvez faire un switch pour rendre NES Games sur SNESC par défaut à / bin / fceumm et laisser la commande kachikachi pour le mode NESC :) Mais, je vais y regarder, plus encore!

**Comment by daPhie79** [comment] 2018-02-24 21:17
this is a retroarch issue though, so i'll close it from here.

**Closed as completed by daPhie79** 2018-02-24 21:17 UTC
Labels: won't fix, can't reproduce
