### ISSUE TITLE
Compatible with BlueRetro

### ISSUE THREAD

**Issue by fermel01** [TeamShinkansen/Hakchi2-CE#426] opened 2022-06-14 16:13 UTC
I wanted to ask if this version is compatible with BlueRetro by Darthcloud (BlueRetro is a multiplayer Bluetooth controllers adapter for various retro game consoles.)?
Since currently there are problems with Hackchi2

thanks for your support!!

**Comment by DanTheMan827** [comment] 2022-06-14 16:39
I take it the device is simulating wii classic controllers?

If the hardware doesn't have pull-up resistors on the data and clock lines, it won't work.

Official Nintendo controllers have these resistors, but not all third party devices do.

The Wii remote doesn't suffer from this same issue though, since that has those resistors in the remote itself in addition to the controller.

If they're missing, you can either solder them to to the system itself, or the adapter.

**Comment by fermel01** [comment] 2022-06-14 17:07
Wii controls are not being used, the controls that are being used are ps4, ps5 and Nintendo switch
I leave a link for more description:

https://github.com/darthcloud/BlueRetro/wiki/BlueRetro-SNES-Mini-Internal-Install

https://www.youtube.com/watch?v=Mb7_PWh9c8s

**Comment by DanTheMan827** [comment] 2022-06-14 17:29
Yes, the BlueRetro in this situation is emulating a classic controller, albeit internally.

If you omitted the pull-up resistors, it will not work, or the behavior will be very erratic.

**Comment by darthcloud** [comment] 2022-06-14 17:46
BlueRetro author here.
The issue is more properly documented here: darthcloud/blueretro#286

Hardware wise everything look fine (pull-up are there) and it work very well with the original Nintendo kernel.

However when using the Hakchi kernel I observe random inputs.

It's not something I would expect to be investigated on the Hakchi side.
Unless you got a quick idea of why behavior would be different vs the original Nintendo FW.

**Comment by DanTheMan827** [comment] 2022-06-14 19:40
@darthcloud a couple changes were made to the clovercon driver to add things like a shortcut combo that acts like the home button, nunchuck support for one-handed players (more so for NES than SNES games), optional toggle for turbo mode.

I've posted more information on the BlueRetro issue

**Comment by darthcloud** [comment] 2022-06-20 13:07
A fix for this is coming in the next release of BlueRetro, this issue can be closed, see darthcloud/blueretro#286 for detail.

Thanks for the help!

**Comment by DanTheMan827** [comment] 2022-06-21 01:03
@fermel01 could you confirm if the latest firmware fixes this issue?

**Closed as completed** 2022-10-04 03:59 UTC
Labels: feature request

**Comment by fermel01** [comment] 2022-10-05 18:11
> @fermel01 could you confirm if the latest firmware fixes this issue?

It is right
