### ISSUE TITLE
Your software has bricked both of my Nintendo Classics

### ISSUE THREAD

**Issue by ghost** [TeamShinkansen/Hakchi2-CE#475] opened 2024-09-23 16:32 UTC
A while ago, I modded my NES and SNES Classic with Hakchi in 2022 (I forgot which version but I believe it was a "CE" build). It worked fine and the games I added worked fine.

Fast forward to today, I'm using Hakchi v3.9.3: it works fine on my Mega Drive mini but for whatever reason, when I try and flash the CFW onto both the NES and SNES Classic, it goes up to 85% complete, then says "Your device is taking a long time to reboot".

I HAVE TRIED EVERY INTERNET SUGGESTION TO UNDO THE BRICKING **_YOUR SOFTWARE_** HAS CAUSED TO MY CONSOLES, I'VE FACTORY RESET BOTH OF THEM, UNINSTALLED THE CFW FROM BOTH OF THEM, HELL, I'VE EVEN **_FLASHED A NEW KERNEL!_** 

However, all it does is:
1) Turn on, no video signal, then shut down immediately (without CFW)
2) Turn on, show Hakchi splash, then shut down (with CFW)

You better tell me how to fix this, otherwise I'm going to rip your throat out.

**Comment by ghost** [comment] 2024-09-23 16:36
Also, for your information: I have no VPN, I even tried this all without the internet (airplane mode) even though I'm on PC and my Firewall is letting you through.

I also downloaded both the uncompressed and compressed kernel files from here: https://github.com/MentalBlank/SNES-Mini-Kernels (latest version, SNES EUR).

**Comment by DanTheMan827** [comment] 2024-09-23 16:54
Unless you can behave civilized, I’m going to close this issue right now.  I also do not appreciate being threatened, so you’re lucky I’m even helping you at all.  People here help in their free time, respect that. 

The device is not bricked, but rather what is more likely is that the kernel version downloaded is mismatched with the operating system.

“Taking too long to reboot” can be caused by a few different things.

- VPN
- Insufficient power getting to the mini
- Windows not installing the correct driver
- Someone using a virtual machine and it not getting both states of the device

First thing to try is to boot into the recovery kernel by selecting `Kernel > Advanced > Boot recovery kernel from RAM` if that works and the system connects to hakchi, you likely didn’t choose the right kernel.  If it doesn’t boot, skip to troubleshooting.

Use the uninstall option while holding shift, and it should prompt for a kernel.  Try the different versions for your mini, the kernel has to match the software that it has.  Alternatively you could download the kernel and matching hsqs file and flash both that kernel and the matching decrypted system software 

**Troubleshooting**

After attempting to enter the recovery kernel and it failing.

Open the device manager, do you see a network device with a name like Remote NDIS, or something containing “classic”, or “samsung”?

if so, can you ping 169.254.13.37?

if the device doesn’t show up in device manager, or you see an unknown device, use a different cable.

**Comment by KMFDManic** [comment] 2024-09-23 17:07
@Oweblow1 your behavior is absolutely unacceptable. Bricking a mini is almost nearly impossible. The demanding attitude of your original topic post absolutely is not at all warranted. 

We wish you the best of luck with your system. But, based on your malicious intent with this post, and a complete breach of Github etiquette and rules, this topic will now be closed. Disrespectful attitude will never ever get one help, sorry to say.

**Closed as completed** 2024-09-23 17:17 UTC
Labels: bug
