### ISSUE TITLE
Game saves Shining Force II and Shining in the Darkness

### ISSUE THREAD

**Issue by ace1973** [TeamShinkansen/Hakchi2-CE#280] opened 2020-01-15 16:29 UTC
**Describe the bug**  

When launching Shining Force II and Shining in the Darkness, both games don't show the option to start a new game, but just the options to 'continue' and 'delete' existing save games. The save games states however are all unusable: for 'Shining in the Darkness' normally the save states are listed as numbers 1, 2 and 3, but now they all say '55' (For Shining Force II they are just gibberish). Deleting a save game and going back to select that erased save games still causes the same error message. 

So far I haven't been able to get past the save menu's and actually play both games. 

Also, checking the box for save games states in Hackchi (and assigning a number of save states) doesn't remedy the situation: I have also tried different file types (.gen, .md and .bin) but all produce the same negative results.  

I just checked and a similar type of error seems to exist for the Phantasy Star II save games. 

And of course, many thanks in advance for solving this!

**Comment by alucard73** [comment] 2020-01-18 21:07
I have no problem with Shining Force 2
For the others yes, as well as Soleil, Phantasy Star 3, Wonder Boy in the Monster Land, Super Hydlide

**Comment by ace1973** [comment] 2020-01-19 09:22
Hi, 
Thanks for your reply. I don't have this problem with Soleil (the others I haven't tested yet). 

Just to be sure, in Shining Force II, at the start of the game (the scene where the witch) you get 4 options ('start', 'continue, 'del' and 'copy') instead of 2 garbled ones? If this is the case, could you please let me know which version of the Shining Force II rom you are using?

**Comment by alucard73** [comment] 2020-01-19 09:58
In Soleil once create the name of the character, when have reset the game, you still have your game in 1?

I use the trad french version of Shining Force 2. I will test a rom in english to see if it is the same or not because on the Trad French version you can delete, copy etc ...

**Comment by madmonkey1907** [comment] 2020-01-19 10:00
Maybe it's stock Sf2? It's a patched rom.
For the issue, press ctrl+f12 in main ce window, settings - dev tools - download latest hakchi, then kernel - install again.
I might need some help with these. With update, you should be able to start most (all?) sram games, but sram saves will not stick. Currently I need to know whether all sram games are affected, or only some of them. To check, press start in main ui to start a game with retroarch. If it works, retroarch should see sram save from m2engage. Sf2 doesn't work that way currently, but I think ps4 does.

**Comment by alucard73** [comment] 2020-01-19 10:10
Hakchi update was done yesterday but the problem is still there.
Soleil and Super Hydlide the sram is recognized with Retroarch but not with M2engage.  I will be testing more games this afternoon.  As indicated on Discord, games with sram problems work in PL

**Comment by madmonkey1907** [comment] 2020-01-19 10:12
I updated it today too, re-download please

**Comment by alucard73** [comment] 2020-01-19 10:26
Once download the hmod, I leave it well in data and I do install / repair?

**Comment by madmonkey1907** [comment] 2020-01-19 10:27
Correct

**Comment by alucard73** [comment] 2020-01-19 10:29
Ok
As soon as I can I re-download it

**Comment by ace1973** [comment] 2020-01-19 10:29
I'm not at home right now, but I'll try the update later this afternoon as well.

**Comment by alucard73** [comment] 2020-01-19 10:38
By cons, Wonderboy is a freeze by pressing Start, I patch the rom for the sram which was on the site of Krizz, the game starts well but the backup not.  This afternoon when I come back, I re-test all that

**Comment by madmonkey1907** [comment] 2020-01-19 10:39
Do not patch it for sram or any other reason besides translation/hack

**Comment by alucard73** [comment] 2020-01-19 10:47
it was just for testing to see if it could correct the problem to give you an idea but I would prefer not to do it either
I'm going to update now and I'm testing some games to see, I'll keep you posted in 10 minutes

**Comment by madmonkey1907** [comment] 2020-01-19 10:48
Oh, sorry then, for testing, good idea actually

**Comment by alucard73** [comment] 2020-01-19 10:54
don't be sorry, I'm still looking for every possible way to understand why a game is not working ;)

Let's go for the tests

**Comment by alucard73** [comment] 2020-01-19 11:17
I tested the games that I had already tested

Phantasy Star 2: Before I had the message that the backups were corrupted when I launched the game, now we can save but M2engage does not recognize it, it is blank but if I launch Retroarch the backup it is recognized

Phantasy Star 3: same problem as Phantasy Star 2 except that now when I save, I have a mush of colors whereas before I didn't

Soleil (Europe, France etc ...): Backup not recognized by M2engage but with Retroarch yes

WonderBoy in the Monster Land: Before I had a freeze by pressing Start to launch the game, now it works except save as before

Super Hydlide: Same as for Soleil

Shining Force 2 (USA): Same as Soleil, except that Shining Force 2 (Trad French) works perfectly

**Comment by madmonkey1907** [comment] 2020-01-19 11:42
Thanks, this will help

**Comment by alucard73** [comment] 2020-01-19 12:01
I forgot

Shining of the Darkness: Before the game said there were backups, now we can do Start but M2engage can't find the backup, Retroarch can't find it either

**Comment by ace1973** [comment] 2020-01-19 12:10
My findings (all US roms, .gen file types):

Crusader of Centy: still doesn't retain save state
Phantasy Star II: no error messages regarding corrupted files any more, but doesn't retain save state
Phantasy Star III: no error messages regarding corrupted files any more, but doesn't retain save state
Shining Force II: correct start-up screen and possible to start the game :-) doesn't retain save state though
Shining in the Darkness: correct start-up screen and possible to start the game :-) doesn't retain save state though

Hope this helps!

**Comment by ace1973** [comment] 2020-01-19 12:43
@madmonkey1907 Thanks so much! I had one remaining question: did the update we install also include retroarch?

**Comment by madmonkey1907** [comment] 2020-01-20 20:33
retroarch only if you install it from km hub. we try not to bundle everything into one giant blob.

**Comment by madmonkey1907** [comment] 2020-01-30 19:13
This should be fixed now. update hakchi and try:
* Press Ctrl+F12 in hakchi CE to unlock the Developper menu.
* Settings > Developper tools > Download Latest Hakchi.
* And finally Kernel > Install / Repair.

**Comment by ace1973** [comment] 2020-01-31 14:46
Hi, thank you so much for your work: i will upload the new Kernel later today and ill let you know what my experiences are.

**Comment by ace1973** [comment] 2020-01-31 17:08
Long story short: all work! Great job :-)

**Closed as completed** 2020-11-29 23:12 UTC
Labels: bug
