### ISSUE TITLE
[Bug] Hakchi2 CE causes loss of internet access.

### ISSUE THREAD

**Issue by DNA64** [TeamShinkansen/Hakchi2-CE#106] opened 2018-06-09 22:10 UTC
**Build:** hakchi2 CE Git Commit ae99075

**Issue:** 
Leaving Hakchi2 CE open for extended periods of time (Example: overnight) results in a loss of internet access. Reproduced (4x) with the same results. Internet still appears to be connected, but unable to access any external sites over LAN.

**O/S:** Windows 7 Ultimate 64-Bit

**Comment by ghost** [comment] 2018-06-11 22:50
thats exactly what i reported last week it was closed. but ye same issue here on win 8.1 x64.
i thought its due to the massive network activity "listening ports"

**Comment by DNA64** [comment] 2018-06-11 22:59
If you press **Ctrl+F12** in Hakchi2 CE it will enable the **_Developer Tools_** option under **_Settings_**. From there you can **_Disable the SSH Listener_** which seems to fix the issue for now.

**Comment by daPhie79** [comment] 2018-06-12 01:42
@AntiFly i didn't connect the dots back then. and @skogaby did explain a bit, and @DanTheMan827 added details. the app is not actively creating UDP traffic, it's simply pinging and listening for llmnr and mdns queries. the added detail about your firewall shutting down the network was confusing.

hopefully the resource leak i found was the cause. in the meantime you can disable the listener like @DNA64 explained. i gave him the workaround. all options in the Developer Tools menu are for very specific fixes and workarounds.

**Comment by daPhie79** [comment] 2018-07-31 18:04
should be fixed in 3.3.0

**Closed as completed by daPhie79** 2018-07-31 18:04 UTC
Labels: bug

**Comment by BananaRama203** [comment] 2018-08-01 08:26
Left 3.30 on overnight and it still knocked out internet. Didn't have time to debug it though. Sorry
